name: Build wiki.libjpel.so static site using MkDocs

on: push

jobs:
  # Performs basic spell-check
  staging:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Install aspell
      run: |
        sudo apt-get install -y aspell
    - name: Run spell check on Markdown
      run: |
        for DOC in $(git diff --name-only HEAD HEAD~1 | grep 'md$'); do 
          echo ${DOC}:
          aspell pipe check --mode=markdown --lang=en --personal=$(pwd)/dictionary.txt < ${DOC} 2> /dev/null | grep '^&' || echo None
          echo
        done
  deploy:
    needs: staging
    runs-on: ubuntu-latest
    environment: production
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Build and publish
      run: |
        mkdocs gh-deploy
